[package]
name = "project_root"
version = "0.1.0"
authors = ["Mat Sadler <mat@sourcetagsandcodes.com>"]
edition = "2018"

[dependencies]
log = "0.4"
stderrlog = "0.5.0"
structopt = { version = "0.3", default-features = false }
